// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6ucheqwey1CYrBWqDdH3OX41leIBKzs0',
    appId: '1:965493720853:web:8a8a026cf2b19678e1cb1c',
    messagingSenderId: '965493720853',
    projectId: 'flutter-chat-app-d186f',
    authDomain: 'flutter-chat-app-d186f.firebaseapp.com',
    storageBucket: 'flutter-chat-app-d186f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgoAteQnemLChXLz2MFExIm0WwcdhYP5o',
    appId: '1:965493720853:android:7840e9e9f9259fd9e1cb1c',
    messagingSenderId: '965493720853',
    projectId: 'flutter-chat-app-d186f',
    storageBucket: 'flutter-chat-app-d186f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR5nFfGbs19mxiNyTnhKcHX787-hC5BGE',
    appId: '1:965493720853:ios:9e3d069731dd458ae1cb1c',
    messagingSenderId: '965493720853',
    projectId: 'flutter-chat-app-d186f',
    storageBucket: 'flutter-chat-app-d186f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR5nFfGbs19mxiNyTnhKcHX787-hC5BGE',
    appId: '1:965493720853:ios:9e3d069731dd458ae1cb1c',
    messagingSenderId: '965493720853',
    projectId: 'flutter-chat-app-d186f',
    storageBucket: 'flutter-chat-app-d186f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6ucheqwey1CYrBWqDdH3OX41leIBKzs0',
    appId: '1:965493720853:web:cd0af1c0c6c66a60e1cb1c',
    messagingSenderId: '965493720853',
    projectId: 'flutter-chat-app-d186f',
    authDomain: 'flutter-chat-app-d186f.firebaseapp.com',
    storageBucket: 'flutter-chat-app-d186f.firebasestorage.app',
  );

}